name: development
on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.19.0'
      - run: go version
      - name: Test
        run: go test -v ./...